package com.tracer.parser;

import com.tracer.model.ExecutionTrace;
import com.tracer.model.MethodCall;

import java.io.*;
import java.util.*;

/**
 * Reads trace data from files generated by the tracer-agent.
 * Handles various file formats: binary, text, JSON, etc.
 */
public class TraceFileReader {
    private static final String TEXT_FORMAT_HEADER = "TRACE_DATA_V1";
    private static final String JSON_FORMAT_MARKER = "{";

    /**
     * Auto-detect format and read trace file
     */
    public ExecutionTrace readTraceFile(File file) throws IOException {
        if (!file.exists()) {
            throw new FileNotFoundException("Trace file not found: " + file.getAbsolutePath());
        }

        // Detect format by file extension
        String filename = file.getName().toLowerCase();
        if (filename.endsWith(".json")) {
            return readJsonTraceFile(file);
        } else if (filename.endsWith(".bin") || filename.endsWith(".trace")) {
            return readBinaryTraceFile(file);
        } else {
            return readTextTraceFile(file);
        }
    }

    /**
     * Read text format trace file
     */
    public ExecutionTrace readTextTraceFile(File file) throws IOException {
        ExecutionTrace trace = new ExecutionTrace();
        List<MethodCall> calls = new ArrayList<>();
        int callOrder = 0;
        long startTime = -1;

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            boolean headerFound = false;

            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;

                // Check for header
                if (line.startsWith(TEXT_FORMAT_HEADER)) {
                    headerFound = true;
                    continue;
                }

                // Parse method call line
                // Format: CLASS|METHOD|SIGNATURE|TIMESTAMP|DURATION|DEPTH|THREAD
                String[] parts = line.split("\\|");
                if (parts.length >= 5) {
                    try {
                        MethodCall call = new MethodCall();
                        call.setClassName(parts[0].trim());
                        call.setMethodName(parts[1].trim());
                        call.setMethodSignature(parts.length > 2 ? parts[2].trim() : "");
                        call.setTimestamp(Long.parseLong(parts[3].trim()));
                        call.setDuration(parts.length > 4 ? Long.parseLong(parts[4].trim()) : 0);
                        call.setDepth(parts.length > 5 ? Integer.parseInt(parts[5].trim()) : 0);
                        call.setThreadName(parts.length > 6 ? parts[6].trim() : "main");
                        call.setCallOrder(callOrder++);

                        if (startTime < 0) {
                            startTime = call.getTimestamp();
                            trace.setEntryClass(call.getClassName());
                            trace.setEntryMethod(call.getMethodName());
                        }

                        calls.add(call);
                    } catch (NumberFormatException e) {
                        System.err.println("Skipping invalid line: " + line);
                    }
                }
            }
        }

        for (MethodCall call : calls) {
            trace.addMethodCall(call);
        }
        trace.setStartTime(startTime);
        trace.setEndTime(startTime + calls.stream().mapToLong(MethodCall::getDuration).sum());
        return trace;
    }

    /**
     * Read binary format trace file
     */
    public ExecutionTrace readBinaryTraceFile(File file) throws IOException {
        ExecutionTrace trace = new ExecutionTrace();
        try (DataInputStream dis = new DataInputStream(new FileInputStream(file))) {
            int callCount = dis.readInt();
            long startTime = dis.readLong();
            trace.setStartTime(startTime);

            for (int i = 0; i < callCount; i++) {
                MethodCall call = readBinaryMethodCall(dis, i);
                trace.addMethodCall(call);
            }

            long endTime = dis.readLong();
            trace.setEndTime(endTime);
        }
        return trace;
    }

    /**
     * Read a single method call from binary stream
     */
    private MethodCall readBinaryMethodCall(DataInputStream dis, int order) throws IOException {
        MethodCall call = new MethodCall();
        call.setClassName(dis.readUTF());
        call.setMethodName(dis.readUTF());
        call.setMethodSignature(dis.readUTF());
        call.setTimestamp(dis.readLong());
        call.setDuration(dis.readLong());
        call.setDepth(dis.readInt());
        call.setThreadName(dis.readUTF());
        call.setCallOrder(order);
        return call;
    }

    /**
     * Read JSON format trace file
     */
    public ExecutionTrace readJsonTraceFile(File file) throws IOException {
        // Simple JSON parsing (in production, use Jackson or Gson)
        ExecutionTrace trace = new ExecutionTrace();
        StringBuilder jsonContent = new StringBuilder();

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                jsonContent.append(line);
            }
        }

        // For now, return empty trace - real implementation would parse JSON
        return trace;
    }

    /**
     * Get file size in human-readable format
     */
    public String getFileSizeReadable(File file) {
        long bytes = file.length();
        if (bytes < 1024) return bytes + " B";
        if (bytes < 1024 * 1024) return String.format("%.1f KB", bytes / 1024.0);
        return String.format("%.1f MB", bytes / (1024.0 * 1024));
    }
}
